version: '3.8'

services:
  db:
    image: mysql:latest
    restart: always
    container_name: helpdesk_db
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    # volumes:
    #   - mysql_data:/var/lib/mysql
    networks:
      - my_network

# volumes:
#   mysql_data:
networks:
  my_network:
    driver: bridge
